name: Deploy Dev

on:
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean install -DskipTests=true

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: 'AKIAUJPP7X57DJ3HD4UC'
          aws-secret-access-key: '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'
          aws-region: 'ap-south-1'

      - name: Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1
        with:
          region: 'ap-south-1'

      - name: Build Docker image
        run: |
          docker build -t 295245430654.dkr.ecr.ap-south-1.amazonaws.com/my-app-repo:latest .

      - name: Push Docker image
        run: |
          docker push 295245430654.dkr.ecr.ap-south-1.amazonaws.com/my-app-repo:latest

      - name: Configure kubectl
        run: |
          aws eks update-kubeconfig --name demo-cluster --region ap-south-1

      - name: Apply Kubernetes manifests
        run: |
          kubectl apply -f k8s/deployment.yaml
          kubectl apply -f k8s/service.yaml
          kubectl apply -f k8s/ingress.yaml
